# Generated by Django 4.2.6 on 2024-03-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='photo',
            field=models.URLField(max_length=256),
        ),
    ]
