# Generated by Django 4.2.6 on 2024-04-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_categories_auction_listings_bids_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='category',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='category',
            field=models.ManyToManyField(related_name='unchartered_category', to='auctions.auction_categories'),
        ),
    ]
