# Generated by Django 4.2.6 on 2024-04-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_listings_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_categories',
            old_name='category',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='category',
            field=models.ManyToManyField(to='auctions.auction_categories'),
        ),
    ]
