# Generated by Django 4.2.6 on 2024-04-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_category_auction_categories_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='category',
        ),
        migrations.AddField(
            model_name='auction_categories',
            name='listings',
            field=models.ManyToManyField(related_name='categories', to='auctions.auction_listings'),
        ),
    ]
