# Generated by Django 4.2.6 on 2024-04-23 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_categories_bids_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='auctions.auction_categories'),
            preserve_default=False,
        ),
    ]
