# Generated by Django 4.2.6 on 2024-04-25 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_listings_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_categories',
            name='listings',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_categories'),
        ),
    ]
