# Generated by Django 4.2.6 on 2024-04-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_user_watchlist_user_x'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_x',
            new_name='user',
        ),
    ]
