# Generated by Django 4.2.6 on 2024-04-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_user_x_watchlist_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlist',
            new_name='User_Watchlist',
        ),
    ]
