# Generated by Django 4.2.6 on 2024-04-27 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='listing_comments',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='listing_comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_comment', to='auctions.auction_listings'),
        ),
        migrations.AddField(
            model_name='comments',
            name='particular_comments',
            field=models.ManyToManyField(related_name='particular_comments', to='auctions.auction_listings'),
        ),
    ]
