# Generated by Django 4.2.6 on 2024-05-02 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_user_watchlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ManyToManyField(to='auctions.auction_listings')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
