# Generated by Django 4.2.6 on 2024-05-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_bidding_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closed_Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('photo', models.URLField(max_length=256)),
            ],
        ),
    ]
