# Generated by Django 4.2.6 on 2024-05-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_closed_auctions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='starting_bid_price',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='bid',
            field=models.ManyToManyField(to='auctions.bids'),
        ),
    ]
