# Generated by Django 4.2.6 on 2024-05-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_bids_starting_bid_price_auction_listings_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding_book',
            old_name='bid',
            new_name='listing',
        ),
    ]
